### PR TITLE
Improving power rendering / adding JOSM and OAPI bonus style sheets

### PR DESCRIPTION
**Pull request by gustavecha**
Hi

@InfosReseaux (twitter) writing

This pull request to improve a bit quickly power colours and rendering
I propose to split power lines and cables in DB and create layers accordingly.
The split can be done on power towers / poles as well

Some work is still pending on adding most advanced features (switches, transformers) but it will be done later.

I've added some styles files coming from other minor projects and which can reinforce openinframap.
OAPI style was involved in this map creation : https://twitter.com/InfosReseaux/status/797866018207043584
http://www.overpass-turbo.eu/s/k19

Feel free to edit / improve committed files ;)

### CODE REVIEW

**Comment by russss** [comment]
I can't merge this as-is because updating mapping.yml requires a database rebuild. I'll try and pull in the .mss stuff separately soon.

**Comment by infosreseaux** [comment]
Thank you Russ,

Understood the point regarding DB rebuild.
Looking forward to see this up & running :)

Don't hesitate to ask if any help needed


All the best
>
>

**Comment by infosreseaux** [comment]
Hi Russ,


A meeting with power operator data scientists was a unique occasion to talk
aout openinframap and show a particular interest in power network
cartography.
Is there anything you need about this particular pull request ?

Feel free to tell me if I can rebuilt the db or test the mapcss defore
publishing it online

All the best

2017-01-30 16:24 GMT+01:00 François Lacombe <fl.infosreseaux@gmail.com>:

> Thank you Russ,
>
> Understood the point regarding DB rebuild.
> Looking forward to see this up & running :)
>
> Don't hesitate to ask if any help needed
>
>
> All the best
>>
>>
>

**Comment by russss** [comment]
OK, I'm now going to close this.

The extra stylesheets now live in the new [contrib repo](https://github.com/openinframap/contrib).

I think most of the other style changes in this PR have now been superseded. If you want to resubmit anything, please make sure it follows the new [contributing guidelines](https://github.com/openinframap/styles/blob/master/.github/CONTRIBUTING.md) as it makes it much easier for me to review PRs if changes to mapping.yml are separate.

**Comment by infosreseaux** [comment]
HI,

Agree with this
Remaining items are covered by issues of the master repo

Thanks for all updates done so far, map quality is really improving !
Power layer may be used by power technician, at least on field with their
mobile devices

All the best

François

2018-01-06 12:05 GMT+01:00 Russ Garrett <notifications@github.com>:

**Pull request closed without merging**
